import { useState } from "react";

import Head from "next/head";
import Image from "next/image";

import { RadioGroup } from "@headlessui/react";

import styles from "../styles/Home.module.css";

export default function Home() {
  let [step, setStep] = useState(0);
  let [social, setSocial] = useState("social");

  const handleClickNext = (event) => {
    if (step < 15) {
      setStep(step + 1);
    }
  };
  const handleClickPrev = (event) => {
    if (step > 0) {
      setStep(step - 1);
    }
  };

  const stepClasses = {
    0: "translate-x-0 [&>:nth-child(1)]:opacity-100",
    1: "translate-x-[-24rem] [&>:nth-child(2)]:opacity-100",
    2: "translate-x-[-48rem] [&>:nth-child(3)]:opacity-100",
    3: "translate-x-[-72rem] [&>:nth-child(4)]:opacity-100",
    4: "translate-x-[-96rem] [&>:nth-child(5)]:opacity-100",
    5: "translate-x-[-120rem] [&>:nth-child(6)]:opacity-100",
    6: "translate-x-[-144rem] [&>:nth-child(7)]:opacity-100",
    7: "translate-x-[-168rem] [&>:nth-child(8)]:opacity-100",
    8: "translate-x-[-192rem] [&>:nth-child(9)]:opacity-100",
    9: "translate-x-[-216rem] [&>:nth-child(10)]:opacity-100",
    10: "translate-x-[-240rem] [&>:nth-child(11)]:opacity-100",
    11: "translate-x-[-264rem] [&>:nth-child(12)]:opacity-100",
    12: "translate-x-[-308rem] [&>:nth-child(13)]:opacity-100",
    13: "translate-x-[-332rem] [&>:nth-child(14)]:opacity-100",
    14: "translate-x-[-356rem] [&>:nth-child(15)]:opacity-100",
    15: "translate-x-[-380rem] [&>:nth-child(16)]:opacity-100",
  };

  const questions = [
    {
      id: "q1",
      text: "When did you last learn a new tool?",
      a1: "Solo",
      a2: "Team",
    },
    {
      id: "q2",
      text: "Do you enjoy going to conferences?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q3",
      text: "Your DMs are...",
      a1: "open",
      a2: "locked",
    },
    {
      id: "q4",
      text: "Do enjoy working solo or on larger projects with a team?",
      a1: "Solo",
      a2: "Team",
    },
    {
      id: "q5",
      text: "Do you enjoy pitching your ideas to an audience?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q6",
      text: "Do you periodically write down your personal goals?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q7",
      text: "Are you always looking for new tools?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q8",
      text: "When your software doesn’t work, you...",
      a1: "hit Google",
      a2: "call someone",
    },
    {
      id: "q9",
      text: "Learning how something work is usually… boring/exciting.",
      a1: "Boring",
      a2: "Exciting",
    },
    {
      id: "q10",
      text: "Do you usually like to learn and teach what you just learned to someone?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q11",
      text: "Do you like to take initiative and come up with plans, ideas or do you usually feel more comfortable to listen to what other people have in mind?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q12",
      text: "Would you prefer to have a regular work-time schedule or to be flexible and change based on projects you have?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q13",
      text: "Would you be up to address financial bureaucracy and be willing to learn about it?",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q14",
      text: "Before doing a project you want to know the budget.",
      a1: "Yes",
      a2: "No",
    },
    {
      id: "q15",
      text: "Do you see yourself usually take the lead and be a good mentor in a group environment or do you prefer to not to?",
      a1: "Yes",
      a2: "No",
    },
  ];

  return (
    <div className="bg-black text-white">
      <Head>
        <title>Designer Lifestyles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between items-center min-h-screen">
        <header className="flex flex-row justify-between w-full max-w-7xl mx-8 my-4">
          <a className="font-display text-2xl" href="">
            <strong>Design</strong> Lifestyles
          </a>
          <a href="" className="text-2xl">
            SHARE
          </a>
        </header>

        <main className="border w-96 h-[30rem] flex flex-col justify-between">
          {/* <div className={stepClasses[step]}> */}
          <div
            className={
              "transition-transform duration-150 flex flex-row h-full [&>*]:opacity-20 " +
              stepClasses[step]
            }
          >
            <div
              id="intro"
              className={
                "px-8 py-12 w-96 h-full flex flex-col items-start justify-evenly gap-4 shrink-0"
              }
            >
              <h1 className="text-xl font-display font-bold">
                Discover your optimal path as a design professional.
              </h1>
              <p>Get a personalized list of resources to become a designer.</p>
              <p>Start with 10 questions.</p>
            </div>
            {questions.map((question) => (
              <div
                key={question.id}
                className={
                  "px-8 py-12 w-96 h-full flex flex-col items-start justify-evenly gap-4 shrink-0 [&:nth-child(" +
                  (step + 1) +
                  ")]:opacity-100"
                }
              >
                <RadioGroup
                  className={"flex flex-col justify-evenly items-start h-full"}
                  value={social}
                  onChange={setSocial}
                >
                  <RadioGroup.Label>{question.text}</RadioGroup.Label>
                  <div className="flex flex-row gap-2 w-full justify-between">
                    <RadioGroup.Option
                      className="flex flex-row items-center justify-center h-16 border rounded-lg w-full"
                      value="1"
                    >
                      {({ checked }) => (
                        <div className="">
                          <div className={checked ? "bg-blue-200" : ""}>
                            {question.a1}
                          </div>
                        </div>
                      )}
                    </RadioGroup.Option>
                    <RadioGroup.Option
                      className="flex flex-row items-center justify-center h-16 border rounded-lg w-full"
                      value="2"
                    >
                      {({ checked }) => (
                        <div className="">
                          <div className={checked ? "bg-blue-200" : ""}>
                            {question.a2}
                          </div>
                        </div>
                      )}
                    </RadioGroup.Option>
                  </div>
                </RadioGroup>
              </div>
            ))}
          </div>
          <div className="px-8 py-12 flex flex-row gap-4 justify-between items-center w-full">
            <button
              onClick={handleClickPrev}
              className="btn text-black py-2 px-8 rounded-full font-display text-xl font-medium flex flex-row justify-center items-center
          cursor-pointer
          transition-[background-color,transform] duration-150
          bg-white/80
          hover:bg-white/100 hover:scale-105
          active:bg-white/60 active:scale-95 active:-rotate-2
          disabled:bg-white/40 disabled:scale-95 disabled:cursor-default
          "
            >
              &larr;
            </button>
            <button
              onClick={handleClickNext}
              className="btn text-black py-2 px-8 rounded-full font-display text-xl font-medium flex flex-row justify-center items-center
          cursor-pointer
          transition-[background-color,transform] duration-150
          bg-white/80
          hover:bg-white/100 hover:scale-105 hover:rotate-2
          active:bg-white/60 active:scale-95 active:-rotate-2
          "
            >
              Next Step
            </button>
          </div>
        </main>

        <aside className="h-px bg-white/20 w-96 flex flex-row justify-start items-center">
          <div className="progress bg-white h-full" width={step * 9.6}></div>
        </aside>

        <footer className="mx-8 my-4">
          <p>
            <span className="text-xs">Created by</span>
            <br />
            <a
              href="https://www.designdisciplin.com/"
              className="font-display font-bold"
            >
              Design Disciplin
            </a>
          </p>
        </footer>
      </div>
    </div>
  );
}
